CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE TABLE tab_status (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Status" text NULL,
        CONSTRAINT "PK_tab_status" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE TABLE tab_user_auth (
        "Id" uuid NOT NULL,
        "Apelido" text NULL,
        "Nome" text NULL,
        "Ativo" boolean NOT NULL,
        CONSTRAINT "PK_tab_user_auth" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE TABLE tab_client (
        "Id" uuid NOT NULL,
        "Nome" character varying(100) NOT NULL,
        "CodigoRadar" text NULL,
        "CEP" character varying(20) NOT NULL,
        "Estado" character varying(4) NOT NULL,
        "Cidade" text NOT NULL,
        "Regiao" character varying(50) NOT NULL,
        "Rua" character varying(100) NOT NULL,
        "NumeroEstabelecimento" text NOT NULL,
        "Cnpj" character varying(14) NOT NULL,
        "ContatoTelefone" character varying(15) NOT NULL,
        "UsuarioCadastroId" uuid NOT NULL,
        "DataHoraCadastro" timestamp with time zone NOT NULL,
        "UsuarioAlteracaoId" uuid NOT NULL,
        "DataHoraAlteracao" timestamp with time zone NOT NULL,
        "Complemento" character varying(50) NULL,
        "NomeContatoClient" character varying(50) NULL,
        CONSTRAINT "PK_tab_client" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_tab_client_tab_user_auth_UsuarioAlteracaoId" FOREIGN KEY ("UsuarioAlteracaoId") REFERENCES tab_user_auth ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_tab_client_tab_user_auth_UsuarioCadastroId" FOREIGN KEY ("UsuarioCadastroId") REFERENCES tab_user_auth ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE TABLE tab_maquina (
        "Id" uuid NOT NULL,
        "CodigoMaquina" text NOT NULL,
        "DescricaoMaquina" character varying(150) NOT NULL,
        "Atribuida" boolean NOT NULL,
        "NumeroSerie" character varying(150) NOT NULL,
        "Ativo" boolean NOT NULL,
        "UsuarioCadastroId" uuid NOT NULL,
        "DataHoraCadastro" timestamp with time zone NOT NULL,
        "UsuarioAlteracaoId" uuid NOT NULL,
        "DataHoraAlteracao" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_tab_maquina" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_tab_maquina_tab_user_auth_UsuarioAlteracaoId" FOREIGN KEY ("UsuarioAlteracaoId") REFERENCES tab_user_auth ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_tab_maquina_tab_user_auth_UsuarioCadastroId" FOREIGN KEY ("UsuarioCadastroId") REFERENCES tab_user_auth ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE TABLE tab_pecas (
        "Id" uuid NOT NULL,
        "CodigoRadar" text NULL,
        "Descricao" text NULL,
        "Unidade" text NULL,
        "Familia" text NULL,
        "Preco" double precision NOT NULL,
        "UsuarioCadastroId" uuid NOT NULL,
        "DataHoraCadastro" timestamp with time zone NOT NULL,
        "UsuarioAlteracaoId" uuid NOT NULL,
        "DataHoraAlteracao" timestamp with time zone NOT NULL,
        "EnderecoImagem" text NULL,
        CONSTRAINT "PK_tab_pecas" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_tab_pecas_tab_user_auth_UsuarioAlteracaoId" FOREIGN KEY ("UsuarioAlteracaoId") REFERENCES tab_user_auth ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_tab_pecas_tab_user_auth_UsuarioCadastroId" FOREIGN KEY ("UsuarioCadastroId") REFERENCES tab_user_auth ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE TABLE tab_sugestao (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SugestacaoManutencao" character varying(1000) NULL,
        "UsuarioSugestacaoId" uuid NOT NULL,
        "DataHoraSugestacao" timestamp with time zone NOT NULL,
        "StatusSugestacao" text NULL,
        CONSTRAINT "PK_tab_sugestao" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_tab_sugestao_tab_user_auth_UsuarioSugestacaoId" FOREIGN KEY ("UsuarioSugestacaoId") REFERENCES tab_user_auth ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE TABLE tab_tecnico (
        "Id" uuid NOT NULL,
        "UsuarioId" uuid NOT NULL,
        "Ativo" boolean NOT NULL,
        CONSTRAINT "PK_tab_tecnico" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_tab_tecnico_tab_user_auth_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES tab_user_auth ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE TABLE tab_maquina_cliente (
        "Id" uuid NOT NULL,
        "MaquinaId" uuid NOT NULL,
        "ClienteId" uuid NOT NULL,
        "Status" integer NOT NULL,
        CONSTRAINT "PK_tab_maquina_cliente" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_tab_maquina_cliente_tab_client_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES tab_client ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_tab_maquina_cliente_tab_maquina_MaquinaId" FOREIGN KEY ("MaquinaId") REFERENCES tab_maquina ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE TABLE "tab_pecaPorMaquina" (
        "Id" uuid NOT NULL,
        "PecaId" uuid NOT NULL,
        "MaquinaId" uuid NOT NULL,
        CONSTRAINT "PK_tab_pecaPorMaquina" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_tab_pecaPorMaquina_tab_maquina_MaquinaId" FOREIGN KEY ("MaquinaId") REFERENCES tab_maquina ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_tab_pecaPorMaquina_tab_pecas_PecaId" FOREIGN KEY ("PecaId") REFERENCES tab_pecas ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE TABLE tab_orcamento (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DescricaoServico" text NULL,
        "ValorOrcamento" double precision NOT NULL,
        "Status" integer NOT NULL,
        "UsuarioCadastroId" uuid NOT NULL,
        "DataHoraCadastro" timestamp with time zone NOT NULL,
        "UsuarioAlteracaoId" uuid NOT NULL,
        "DataHoraAlteracao" timestamp with time zone NOT NULL,
        "MaquinaId" uuid NOT NULL,
        "MaquinaClienteId" uuid NOT NULL,
        CONSTRAINT "PK_tab_orcamento" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_tab_orcamento_tab_maquina_MaquinaId" FOREIGN KEY ("MaquinaId") REFERENCES tab_maquina ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_tab_orcamento_tab_maquina_cliente_MaquinaClienteId" FOREIGN KEY ("MaquinaClienteId") REFERENCES tab_maquina_cliente ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_tab_orcamento_tab_user_auth_UsuarioAlteracaoId" FOREIGN KEY ("UsuarioAlteracaoId") REFERENCES tab_user_auth ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_tab_orcamento_tab_user_auth_UsuarioCadastroId" FOREIGN KEY ("UsuarioCadastroId") REFERENCES tab_user_auth ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE TABLE "tab_pecasMaquinaEOrcamento" (
        "Id" uuid NOT NULL,
        "MaquinaId" uuid NOT NULL,
        "Quantidade" double precision NOT NULL,
        "PecaId" uuid NOT NULL,
        "Conserto" boolean NOT NULL,
        "Troca" boolean NOT NULL,
        "Reaproveitamento" boolean NOT NULL,
        "OrcamentoId" integer NOT NULL,
        CONSTRAINT "PK_tab_pecasMaquinaEOrcamento" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_tab_pecasMaquinaEOrcamento_tab_maquina_MaquinaId" FOREIGN KEY ("MaquinaId") REFERENCES tab_maquina ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_tab_pecasMaquinaEOrcamento_tab_orcamento_OrcamentoId" FOREIGN KEY ("OrcamentoId") REFERENCES tab_orcamento ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_tab_pecasMaquinaEOrcamento_tab_pecas_PecaId" FOREIGN KEY ("PecaId") REFERENCES tab_pecas ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE TABLE "tab_statusOrcamento" (
        "Id" uuid NOT NULL,
        "OrcamentoId" integer NOT NULL,
        "StatusId" integer NOT NULL,
        "DataHoraInicio" timestamp with time zone NOT NULL,
        "DataHoraFim" timestamp with time zone NOT NULL,
        "Observacao" character varying(2000) NULL,
        CONSTRAINT "PK_tab_statusOrcamento" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_tab_statusOrcamento_tab_orcamento_OrcamentoId" FOREIGN KEY ("OrcamentoId") REFERENCES tab_orcamento ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_tab_statusOrcamento_tab_status_StatusId" FOREIGN KEY ("StatusId") REFERENCES tab_status ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE TABLE "tab_tecnicoManutencao" (
        "Id" uuid NOT NULL,
        "TecnicoId" uuid NOT NULL,
        "OrcamentoId" integer NOT NULL,
        CONSTRAINT "PK_tab_tecnicoManutencao" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_tab_tecnicoManutencao_tab_orcamento_OrcamentoId" FOREIGN KEY ("OrcamentoId") REFERENCES tab_orcamento ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_tab_tecnicoManutencao_tab_tecnico_TecnicoId" FOREIGN KEY ("TecnicoId") REFERENCES tab_tecnico ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE TABLE "tab_tecnicoOrcamento" (
        "Id" uuid NOT NULL,
        "TecnicoId" uuid NOT NULL,
        "OrcamentoId" integer NOT NULL,
        CONSTRAINT "PK_tab_tecnicoOrcamento" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_tab_tecnicoOrcamento_tab_orcamento_OrcamentoId" FOREIGN KEY ("OrcamentoId") REFERENCES tab_orcamento ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_tab_tecnicoOrcamento_tab_tecnico_TecnicoId" FOREIGN KEY ("TecnicoId") REFERENCES tab_tecnico ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE TABLE "tab_usuarioApontamentoStatusFim" (
        "Id" uuid NOT NULL,
        "StatusOrcamentoId" uuid NOT NULL,
        "UsuarioApontamentoFimId" uuid NOT NULL,
        CONSTRAINT "PK_tab_usuarioApontamentoStatusFim" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_tab_usuarioApontamentoStatusFim_tab_statusOrcamento_StatusO~" FOREIGN KEY ("StatusOrcamentoId") REFERENCES "tab_statusOrcamento" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_tab_usuarioApontamentoStatusFim_tab_user_auth_UsuarioAponta~" FOREIGN KEY ("UsuarioApontamentoFimId") REFERENCES tab_user_auth ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE TABLE "tab_usuarioApontamentoStatusInicio" (
        "Id" uuid NOT NULL,
        "StatusOrcamentoId" uuid NOT NULL,
        "UsuarioApontamentoInicioId" uuid NOT NULL,
        CONSTRAINT "PK_tab_usuarioApontamentoStatusInicio" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_tab_usuarioApontamentoStatusInicio_tab_statusOrcamento_Stat~" FOREIGN KEY ("StatusOrcamentoId") REFERENCES "tab_statusOrcamento" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_tab_usuarioApontamentoStatusInicio_tab_user_auth_UsuarioApo~" FOREIGN KEY ("UsuarioApontamentoInicioId") REFERENCES tab_user_auth ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE INDEX "IX_tab_client_UsuarioAlteracaoId" ON tab_client ("UsuarioAlteracaoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE INDEX "IX_tab_client_UsuarioCadastroId" ON tab_client ("UsuarioCadastroId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE INDEX "IX_tab_maquina_UsuarioAlteracaoId" ON tab_maquina ("UsuarioAlteracaoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE INDEX "IX_tab_maquina_UsuarioCadastroId" ON tab_maquina ("UsuarioCadastroId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE INDEX "IX_tab_maquina_cliente_ClienteId" ON tab_maquina_cliente ("ClienteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE UNIQUE INDEX "IX_tab_maquina_cliente_MaquinaId" ON tab_maquina_cliente ("MaquinaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE INDEX "IX_tab_orcamento_MaquinaClienteId" ON tab_orcamento ("MaquinaClienteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE INDEX "IX_tab_orcamento_MaquinaId" ON tab_orcamento ("MaquinaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE INDEX "IX_tab_orcamento_UsuarioAlteracaoId" ON tab_orcamento ("UsuarioAlteracaoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE INDEX "IX_tab_orcamento_UsuarioCadastroId" ON tab_orcamento ("UsuarioCadastroId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE INDEX "IX_tab_pecaPorMaquina_MaquinaId" ON "tab_pecaPorMaquina" ("MaquinaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE INDEX "IX_tab_pecaPorMaquina_PecaId" ON "tab_pecaPorMaquina" ("PecaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE INDEX "IX_tab_pecas_UsuarioAlteracaoId" ON tab_pecas ("UsuarioAlteracaoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE INDEX "IX_tab_pecas_UsuarioCadastroId" ON tab_pecas ("UsuarioCadastroId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE INDEX "IX_tab_pecasMaquinaEOrcamento_MaquinaId" ON "tab_pecasMaquinaEOrcamento" ("MaquinaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE INDEX "IX_tab_pecasMaquinaEOrcamento_OrcamentoId" ON "tab_pecasMaquinaEOrcamento" ("OrcamentoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE INDEX "IX_tab_pecasMaquinaEOrcamento_PecaId" ON "tab_pecasMaquinaEOrcamento" ("PecaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE INDEX "IX_tab_statusOrcamento_OrcamentoId" ON "tab_statusOrcamento" ("OrcamentoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE INDEX "IX_tab_statusOrcamento_StatusId" ON "tab_statusOrcamento" ("StatusId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE INDEX "IX_tab_sugestao_UsuarioSugestacaoId" ON tab_sugestao ("UsuarioSugestacaoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE INDEX "IX_tab_tecnico_UsuarioId" ON tab_tecnico ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE UNIQUE INDEX "IX_tab_tecnicoManutencao_OrcamentoId" ON "tab_tecnicoManutencao" ("OrcamentoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE INDEX "IX_tab_tecnicoManutencao_TecnicoId" ON "tab_tecnicoManutencao" ("TecnicoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE UNIQUE INDEX "IX_tab_tecnicoOrcamento_OrcamentoId" ON "tab_tecnicoOrcamento" ("OrcamentoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE INDEX "IX_tab_tecnicoOrcamento_TecnicoId" ON "tab_tecnicoOrcamento" ("TecnicoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE UNIQUE INDEX "IX_tab_usuarioApontamentoStatusFim_StatusOrcamentoId" ON "tab_usuarioApontamentoStatusFim" ("StatusOrcamentoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE INDEX "IX_tab_usuarioApontamentoStatusFim_UsuarioApontamentoFimId" ON "tab_usuarioApontamentoStatusFim" ("UsuarioApontamentoFimId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE UNIQUE INDEX "IX_tab_usuarioApontamentoStatusInicio_StatusOrcamentoId" ON "tab_usuarioApontamentoStatusInicio" ("StatusOrcamentoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    CREATE INDEX "IX_tab_usuarioApontamentoStatusInicio_UsuarioApontamentoInicio~" ON "tab_usuarioApontamentoStatusInicio" ("UsuarioApontamentoInicioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230928021558_FirstMigration') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20230928021558_FirstMigration', '7.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231017195241_AdicionaColunaUnidadeTabelaMaquina') THEN
    ALTER TABLE tab_maquina ADD "Unidade" text NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231017195241_AdicionaColunaUnidadeTabelaMaquina') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20231017195241_AdicionaColunaUnidadeTabelaMaquina', '7.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231019191308_AdicionadoTabelaParaDiarioDoOrcamento') THEN
    CREATE TABLE "tab_diarioOrcamento" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "NumeroOrcamentoId" integer NOT NULL,
        "Informacao" text NULL,
        "Tag" text NULL,
        "OrcamentoId" integer NULL,
        "UsuarioApontamentoId" uuid NOT NULL,
        "DataHoraApontamento" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_tab_diarioOrcamento" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_tab_diarioOrcamento_tab_orcamento_OrcamentoId" FOREIGN KEY ("OrcamentoId") REFERENCES tab_orcamento ("Id"),
        CONSTRAINT "FK_tab_diarioOrcamento_tab_user_auth_UsuarioApontamentoId" FOREIGN KEY ("UsuarioApontamentoId") REFERENCES tab_user_auth ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231019191308_AdicionadoTabelaParaDiarioDoOrcamento') THEN
    CREATE INDEX "IX_tab_diarioOrcamento_OrcamentoId" ON "tab_diarioOrcamento" ("OrcamentoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231019191308_AdicionadoTabelaParaDiarioDoOrcamento') THEN
    CREATE INDEX "IX_tab_diarioOrcamento_UsuarioApontamentoId" ON "tab_diarioOrcamento" ("UsuarioApontamentoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231019191308_AdicionadoTabelaParaDiarioDoOrcamento') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20231019191308_AdicionadoTabelaParaDiarioDoOrcamento', '7.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231019204656_atualizacaoAgora') THEN
    ALTER TABLE "tab_diarioOrcamento" DROP CONSTRAINT "FK_tab_diarioOrcamento_tab_orcamento_OrcamentoId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231019204656_atualizacaoAgora') THEN
    ALTER TABLE "tab_diarioOrcamento" DROP COLUMN "NumeroOrcamentoId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231019204656_atualizacaoAgora') THEN
    UPDATE "tab_diarioOrcamento" SET "OrcamentoId" = 0 WHERE "OrcamentoId" IS NULL;
    ALTER TABLE "tab_diarioOrcamento" ALTER COLUMN "OrcamentoId" SET NOT NULL;
    ALTER TABLE "tab_diarioOrcamento" ALTER COLUMN "OrcamentoId" SET DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231019204656_atualizacaoAgora') THEN
    ALTER TABLE "tab_diarioOrcamento" ADD CONSTRAINT "FK_tab_diarioOrcamento_tab_orcamento_OrcamentoId" FOREIGN KEY ("OrcamentoId") REFERENCES tab_orcamento ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231019204656_atualizacaoAgora') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20231019204656_atualizacaoAgora', '7.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231025160321_AdicionadoColunaExternoNoOrcamento') THEN
    ALTER TABLE tab_orcamento ADD "Externo" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231025160321_AdicionadoColunaExternoNoOrcamento') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20231025160321_AdicionadoColunaExternoNoOrcamento', '7.0.12');
    END IF;
END $EF$;
COMMIT;

